require('dotenv').config();
const express = require('express');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const cors = require('cors');
const bodyParser = require('body-parser');
const { Pool } = require('@neondatabase/serverless');
const crypto = require('crypto');

const app = express();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// Database — Postgres only (optional; skipped if DATABASE_URL not set)
let db = null;
if (process.env.DATABASE_URL) {
  db = new Pool({ connectionString: process.env.DATABASE_URL });
  db.query(`CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    stripe_session_id TEXT UNIQUE,
    confirmation_code TEXT UNIQUE,
    speech_data TEXT,
    speech_text TEXT,
    is_paid INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )`).catch(err => console.error('Postgres init error:', err));
}

async function runQuery(query, params = []) {
  if (!db) return null;
  let pgQuery = query;
  params.forEach((_, i) => { pgQuery = pgQuery.replace('?', `$${i + 1}`); });
  return db.query(pgQuery, params);
}

async function getQuery(query, params = []) {
  if (!db) return null;
  let pgQuery = query;
  params.forEach((_, i) => { pgQuery = pgQuery.replace('?', `$${i + 1}`); });
  const res = await db.query(pgQuery, params);
  return res.rows[0];
}

app.use(cors());
app.use(express.static('public'));

// ===== SPEECH GENERATION WITH GEMINI =====
async function generateSpeech(data) {
  const {
    yourName, yourRole, partner1, partner2, weddingDate,
    yearsKnown, relationship, memory1, memory2, memory3,
    word1, word2, word3, tone, avoid, length
  } = data;

  const wordCount = length === '2 minutes' ? '250-300 words'
    : length === '6 minutes' ? '800-850 words'
    : '500-550 words';

  const avoidNote = avoid ? `\nTopics to avoid entirely: ${avoid}` : '';

  const prompt = `Write a personalised wedding speech with the following details:

Speaker: ${yourName} (${yourRole})
Couple: ${partner1} and ${partner2}
How long they have known them: ${yearsKnown}
Relationship to the couple: ${relationship}

Three memories or stories to weave in naturally:
1. ${memory1}
2. ${memory2}
3. ${memory3}

Three words that capture the couple: ${word1}, ${word2}, ${word3}
Tone: ${tone}${avoidNote}
Target length: ${wordCount}

Write the speech as if ${yourName} is delivering it live at the wedding. Make it feel warm, genuine, and personal — not generic. Open naturally, weave the memories in as real stories, celebrate the couple using those three words, and close with a heartfelt toast to ${partner1} and ${partner2}. Do not use any placeholder text.`;

  const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
  const result = await model.generateContent(prompt);
  return result.response.text();
}

// 1. Generate Speech
app.post('/generate-speech', bodyParser.json(), async (req, res) => {
  try {
    const speech = await generateSpeech(req.body);
    res.json({ speech });
  } catch (err) {
    console.error('Speech generation error:', err);
    res.status(500).json({ error: 'Failed to generate speech. Please try again.' });
  }
});

// 2. Create Stripe Checkout Session
app.post('/create-checkout-session', bodyParser.json(), async (req, res) => {
  const { speechData, speechText } = req.body;
  try {
    const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      line_items: [{
        price_data: {
          currency: 'gbp',
          product_data: {
            name: 'Personalised Wedding Speech',
            description: 'Custom speech generated by Say It Perfectly',
          },
          unit_amount: 1500,
        },
        quantity: 1,
      }],
      mode: 'payment',
      success_url: `${req.headers.origin}/?success=true&session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${req.headers.origin}/?canceled=true`,
    });

    await runQuery(
      'INSERT INTO orders (stripe_session_id, speech_data, speech_text) VALUES (?, ?, ?)',
      [session.id, JSON.stringify(speechData), speechText]
    ).catch(err => console.error('DB insert error:', err));

    res.json({ id: session.id });
  } catch (error) {
    console.error('Stripe error:', error);
    res.status(500).json({ error: error.message });
  }
});

// 3. Stripe Webhook
app.post('/webhook', bodyParser.raw({ type: 'application/json' }), async (req, res) => {
  const sig = req.headers['stripe-signature'];
  let event;
  try {
    event = stripe.webhooks.constructEvent(req.body, sig, process.env.STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    return res.status(400).send(`Webhook Error: ${err.message}`);
  }

  if (event.type === 'checkout.session.completed') {
    const session = event.data.object;
    const confirmationCode = 'SIP-' + crypto.randomBytes(3).toString('hex').toUpperCase();
    await runQuery(
      'UPDATE orders SET is_paid = 1, confirmation_code = ? WHERE stripe_session_id = ?',
      [confirmationCode, session.id]
    ).catch(err => console.error('DB update error:', err));
  }

  res.json({ received: true });
});

// 4. Verify Code
app.post('/verify-code', bodyParser.json(), async (req, res) => {
  const { code } = req.body;

  if (code === 'SIP-DEMO') {
    try {
      const demoData = {
        yourName: 'Alex', yourRole: 'Best Man',
        partner1: 'Sam', partner2: 'Jordan',
        weddingDate: '', yearsKnown: '15 years',
        relationship: 'Best friends since university — I was there from the very first date.',
        memory1: 'That chaotic weekend in the Highlands where we got completely lost and Sam stayed completely calm the whole time.',
        memory2: 'When Sam called me at midnight to ask for help planning the proposal — I had to keep the secret for three weeks.',
        memory3: 'Watching Jordan walk into the room at their first flat viewing together and seeing Sam light up.',
        word1: 'loyal', word2: 'hilarious', word3: 'kind',
        tone: 'mix of both', avoid: '', length: '4 minutes'
      };
      const speechText = await generateSpeech(demoData);
      return res.json({ success: true, speechText });
    } catch (err) {
      console.error('Demo speech error:', err);
      return res.status(500).json({ error: 'Failed to generate demo speech.' });
    }
  }

  try {
    const row = await getQuery(
      'SELECT speech_data, speech_text FROM orders WHERE confirmation_code = ? AND is_paid = 1',
      [code]
    );
    if (row) {
      res.json({
        success: true,
        speechData: typeof row.speech_data === 'string' ? JSON.parse(row.speech_data) : row.speech_data,
        speechText: row.speech_text
      });
    } else {
      res.json({ success: false, message: 'Invalid or unpaid code' });
    }
  } catch (err) {
    console.error('Verify error:', err);
    res.status(500).json({ error: 'Database error' });
  }
});

if (process.env.NODE_ENV !== 'production') {
  const PORT = process.env.PORT || 3000;
  app.listen(PORT, '0.0.0.0', () => console.log(`Server running on http://0.0.0.0:${PORT}`));
}

module.exports = app;
