require('dotenv').config();
const express = require('express');
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const cors = require('cors');
const bodyParser = require('body-parser');
const sqlite3 = require('sqlite3').verbose();
const path = require('path');
const crypto = require('crypto');

const app = express();
const db = new sqlite3.Database('./database.sqlite');

// Initialize Database
db.serialize(() => {
  db.run(`CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    stripe_session_id TEXT UNIQUE,
    confirmation_code TEXT UNIQUE,
    speech_data TEXT,
    is_paid INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`);
});

app.use(cors());
app.use(express.static('public'));

// 1. Create Stripe Checkout Session
app.post('/create-checkout-session', bodyParser.json(), async (req, res) => {
  const { speechData } = req.body;

  try {
    const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      line_items: [{
        price_data: {
          currency: 'gbp',
          product_data: {
            name: 'Personalised Wedding Speech',
            description: 'Custom speech generated by Say It Perfectly',
          },
          unit_amount: 1500, // £15.00
        },
        quantity: 1,
      }],
      mode: 'payment',
      success_url: `${req.headers.origin}/?success=true&session_id={CHECKOUT_SESSION_ID}`,
      cancel_url: `${req.headers.origin}/?canceled=true`,
    });

    // Generate temporary record
    db.run(
      'INSERT INTO orders (stripe_session_id, speech_data) VALUES (?, ?)',
      [session.id, JSON.stringify(speechData)],
      (err) => {
        if (err) console.error('DB Error:', err);
      }
    );

    res.json({ id: session.id });
  } catch (error) {
    console.error('Stripe Error:', error);
    res.status(500).json({ error: error.message });
  }
});

// 2. Stripe Webhook for Payment Confirmation
app.post('/webhook', bodyParser.raw({type: 'application/json'}), async (req, res) => {
  const sig = req.headers['stripe-signature'];
  let event;

  try {
    event = stripe.webhooks.constructEvent(req.body, sig, process.env.STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    return res.status(400).send(`Webhook Error: ${err.message}`);
  }

  if (event.type === 'checkout.session.completed') {
    const session = event.data.object;
    const confirmationCode = 'SIP-' + crypto.randomBytes(3).toString('hex').toUpperCase();

    db.run(
      'UPDATE orders SET is_paid = 1, confirmation_code = ? WHERE stripe_session_id = ?',
      [confirmationCode, session.id],
      (err) => {
        if (err) console.error('DB Update Error:', err);
      }
    );
  }

  res.json({received: true});
});

// 3. Verify Code Endpoint
app.post('/verify-code', bodyParser.json(), (req, res) => {
  const { code } = req.body;

  db.get(
    'SELECT speech_data FROM orders WHERE confirmation_code = ? AND is_paid = 1',
    [code],
    (err, row) => {
      if (err) return res.status(500).json({ error: 'Database error' });
      if (row) {
        res.json({ success: true, speechData: JSON.parse(row.speech_data) });
      } else {
        res.json({ success: false, message: 'Invalid or unpaid code' });
      }
    }
  );
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server running on http://0.0.0.0:${PORT}`);
});
